services:
    # laravel.test:
    #     container_name: radio-sail
    #     build:
    #         context: ./docker/8.2
    #         dockerfile: Dockerfile
    #         args:
    #             WWWGROUP: "${WWWGROUP}"
    #     image: sail-8.2/app
    #     extra_hosts:
    #         - "host.docker.internal:host-gateway"
    #     ports:
    #         - "${APP_PORT:-80}:80"
    #         - "${VITE_PORT:-5173}:${VITE_PORT:-5173}"
    #     environment:
    #         WWWUSER: "${WWWUSER}"
    #         LARAVEL_SAIL: 1
    #         XDEBUG_MODE: "${SAIL_XDEBUG_MODE:-off}"
    #         XDEBUG_CONFIG: "${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}"
    #         IGNITION_LOCAL_SITES_PATH: "${PWD}"
    #     volumes:
    #         - ".:/var/www/html"
    #     networks:
    #         - sail
    #     depends_on:
    #         - pgsql
    #         - redis
    #         - mailpit
    #         - selenium

    nginx:
        container_name: radio-nginx
        build:
            context: "./docker/nginx"
        depends_on:
            - php-fpm
        networks:
            - sail
        ports:
            - "${NGINX_HOST_HTTPS_PORT}:443"
            - "${NGINX_HOST_HTTP_PORT}:80"
        volumes:
            - "${NGINX_SSL_PATH}:/etc/nginx/ssl"
            - "${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}"
            - "${NGINX_HOST_LOG_PATH}:/var/log/nginx"
            - "${NGINX_SITES_PATH}:/etc/nginx/sites-available"
    php-fpm:
        container_name: radio-php-fpm
        build:
            context: "./docker/php-fpm"
        volumes:
            - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
        networks:
            - sail
        expose:
            - 9000
    pgsql:
        container_name: radio-pgsql
        image: "postgres:15"
        ports:
            - "${FORWARD_DB_PORT:-5432}:5432"
        environment:
            PGPASSWORD: "${DB_PASSWORD:-secret}"
            POSTGRES_DB: "${DB_DATABASE}"
            POSTGRES_USER: "${DB_USERNAME}"
            POSTGRES_PASSWORD: "${DB_PASSWORD:-secret}"
        volumes:
            - "sail-pgsql:/var/lib/postgresql/data"
            - "./docker/pgsql/create-testing-database.sql:/docker-entrypoint-initdb.d/10-create-testing-database.sql"
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - pg_isready
                - "-q"
                - "-d"
                - "${DB_DATABASE}"
                - "-U"
                - "${DB_USERNAME}"
            retries: 3
            timeout: 5s
    redis:
        container_name: radio-redis
        image: "redis:alpine"
        ports:
            - "${FORWARD_REDIS_PORT:-6379}:6379"
        volumes:
            - "sail-redis:/data"
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s
    mailpit:
        container_name: radio-mailpit
        image: "axllent/mailpit:latest"
        ports:
            - "${FORWARD_MAILPIT_PORT:-1025}:1025"
            - "${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025"
        networks:
            - sail
    selenium:
        container_name: radio-selenium
        image: selenium/standalone-chrome
        extra_hosts:
            - "host.docker.internal:host-gateway"
        volumes:
            - "/dev/shm:/dev/shm"
        networks:
            - sail
networks:
    sail:
        driver: bridge
volumes:
    sail-pgsql:
        driver: local
    sail-redis:
        driver: local
