version: "3.7"
networks:
  default:
    external:
      name: nginx-proxy
volumes:
  storage:
  dbdata:

services:
  php:
    image: app-php:latest
    env_file:
        - ../src/.env
    restart: unless-stopped
    depends_on:
      - postgres
    volumes:
      - storage:/var/www/html/storage
  nginx:
    container_name: app-nginx
    image:app-nginx:latest
    restart: unless-stopped
    depends_on:
      - php
    environment:
      VIRTUAL_HOST: ${HOSTNAME}
      LETSENCRYPT_HOST: ${HOSTNAME}
  postgres:
    container_name: app-postgres
    image: postgres:13-alpine
    restart: unless-stopped
    volumes:
      - dbdata:/var/lib/postgresql/data"
    env_file:
      - ../src/.env
  cron:
    container_name: app-cron
    image: app-php:latest
    restart: unless-stopped
    depends_on:
      - postgres
    command: [crond", "-f"]
  queue:
    container_name: app-queue
    image: app-php:latest
    restart: unless-stopped
    depends_on:
      - postgres
    command: 'php artisan queue:work --queue=default'