version: "3.7"
networks:
  default:
    external:
      name: nginx-proxy
volumes:
  storage:
  db-data:

services:
  php:
    container_name: app-php
    image: app-php:latest
    restart: unless-stopped
    depends_on:
      - postgres
    volumes:
      - storage:/var/www/storage
  nginx:
    container_name: app-nginx
    image: app-nginx:latest
    restart: unless-stopped
    depends_on:
      - php
    environment:
      VIRTUAL_HOST: ${APP_URL}
      LETSENCRYPT_HOST: ${APP_URL}
  postgres:
    container_name: app-postgres
    image: postgres:13-alpine
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
  cron:
    container_name: app-cron
    image: app-php:latest
    restart: unless-stopped
    command: [ "crond", "-f"]
    depends_on:
      - postgres
  queue:
    container_name: app-queue
    image: app-php:latest
    restart: unless-stopped
    depends_on:
      - postgres
    command: 'php artisan queue:work --queue=default'
