version: "3.7"
#services:
#  node:
#    container_name: app-npm
#    image: node:14
#    restart: unless-stopped
#    volumes:
#      - ../src:/var/www
#      - node_modules:/var/www/node_modules
#    working_dir: /var/www
#    command: sh -c 'npm install && npm run watch-poll'
#  mailhog:
#    container_name: app-mailhog
#    image: mailhog/mailhog:latest
#    ports:
#      - 1025:1025
#      - 8025:8025
#volumes:
#  node_modules: